##################### POST ##########################################
GET http://localhost:3000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTU5MTgyODA5MywiZXhwIjoxNTkxOTE0NDkzfQ.WKzBx3jsPd0TIzhMi3NKHpAtdW039M0DComrIYEcITM


###
GET http://localhost:3000/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTU5MTgyODA5MywiZXhwIjoxNTkxOTE0NDkzfQ.WKzBx3jsPd0TIzhMi3NKHpAtdW039M0DComrIYEcITM

###
POST http://localhost:3000/posts/new/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTU5MTY5NjcwNSwiZXhwIjoxNTkxNzgzMTA1fQ.WyOMgYlJrJ_sc7MqVW-R5bKdbRMOUErKtASr7HAlQXs

{
    "UserId": 1,
    "title": "gibson",
    "content":"gibson Musical Instruments Corporation, nommé initialement Fender's Radio Service puis Fender Electric Instrument Manufacturing Company, est une société créée par Leo Fender aux États-Unis dans les années 1940.",
    "url_image":""
}

###
PUT http://localhost:3000/posts/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTUxNjM2NiwiZXhwIjoxNTkxNjAyNzY2fQ.Ildfil9cM7Ngrn3G_9Kva2Kk_Z4KzD6KotwygdYakQk

{
    "userId": 1,
    "title": "nouveau contenu",
    "content": "contenu modifié",
    "url_image":""
}


### 
DELETE http://localhost:3000/posts/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTU5MTgyODA5MywiZXhwIjoxNTkxOTE0NDkzfQ.WKzBx3jsPd0TIzhMi3NKHpAtdW039M0DComrIYEcITM







##################### USER ##########################################
###
GET http://localhost:3000/user/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTU5MTgyODA5MywiZXhwIjoxNTkxOTE0NDkzfQ.WKzBx3jsPd0TIzhMi3NKHpAtdW039M0DComrIYEcITM


###
POST http://localhost:3000/user/signup/
Content-Type: application/json

{
    "firstname": "martin",
    "lastname": "dupond",
    "mail": "martin@dupond.com",
    "mdp": "Azerty1@"
}


###
POST http://localhost:3000/user/login/
Content-Type: application/json

{
    "mail": "admin@admin.com",
    "mdp": "Azerty1@"
}


###
DELETE http://localhost:3000/user/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTU5MTUzNjczNywiZXhwIjoxNTkxNjIzMTM3fQ.DQoYExbmfVJhm_x7JYrxtlKJCq4kl383TM38i8uPdqs

{
    "userId": 2,
    "mail": "user@user.com",
    "mdp": "Azerty1@"
}


##################### COMMENTS ##########################################
###
POST http://localhost:3000/comments/new/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTU5MTUzNTkzMCwiZXhwIjoxNTkxNjIyMzMwfQ.uwgG8WoQlxYTV8ozEwZhqOs3PPMXHNN4PklzrvD2jV8

{
    "content":"merci !", 
    "PostId": 1,
    "UserId": 3
}

# ###
# GET http://localhost:3000/comments/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTQyODc4MSwiZXhwIjoxNTkxNTE1MTgxfQ.IlT_GCX83Nq-oaq6ziCWvahyzjsGdFDD_AP3MjsuaF8

# {
#     "content":" Nouveau commentaire", 
#     "PostId": 1,
#     "UserId": 1
# }


### 
DELETE http://localhost:3000/comments/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTU5MTUzNTkzMCwiZXhwIjoxNTkxNjIyMzMwfQ.uwgG8WoQlxYTV8ozEwZhqOs3PPMXHNN4PklzrvD2jV8



###
PUT http://localhost:3000/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTQyODc4MSwiZXhwIjoxNTkxNTE1MTgxfQ.IlT_GCX83Nq-oaq6ziCWvahyzjsGdFDD_AP3MjsuaF8

{
    "content": "lorem"
}


