GET http://localhost:3000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTU5MTI5OTA3NSwiZXhwIjoxNTkxMzg1NDc1fQ.hyPob8qnq5snR5B1A7KUVhILSezg3W-ZE4l1krItQ90


##################### POST ###

###
POST http://localhost:3000/user/login/
Content-Type: application/json

{
    "mail": "aze@aze.com",
    "mdp": "aze"
}

###
POST http://localhost:3000/posts/new/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTI5OTE5MCwiZXhwIjoxNTkxMzg1NTkwfQ._5pHSJ0MwpHir0hLTotD8A8C7tQTBj6KS36mNT7_sno

{
    "UserId": 1,
    "title": "voici un premier post",
    "content": "em ad adulescentiam perduxissent, dirimi tamen interdum contentione vel uxoriae condicionis vel commodi alicuius, quod idem adipisci uterque non posset. Quod si qui longius in amicitia provecti essent, tamen saepe labefactari, si in honoris contentionem incidissent; pestem enim nullam maiorem esse ",
    "url_image":"https://media.giphy.com/media/rY93u9tQbybks/giphy.gif"
}

###
POST http://localhost:3000/comments/new/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTI5OTE5MCwiZXhwIjoxNTkxMzg1NTkwfQ._5pHSJ0MwpHir0hLTotD8A8C7tQTBj6KS36mNT7_sno

{
    "content":" premier commentaire", 
    "PostId": 1,
    "UserId": 1
}

###
POST http://localhost:3000/user/signup/
Content-Type: application/json

{
    "firstname": "aze",
    "lastname": "aze",
    "mail": "aze@aze.com",
    "mdp": "aze"
}





##################### DELETE ###
### 
DELETE http://localhost:3000/posts/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTU5MTI5ODY4MSwiZXhwIjoxNTkxMzg1MDgxfQ.sXKh0a07qG6g56N1ZiHVtqqZad1JQH7saUSXMcoFWY0

{
    "id": 5
}

### 
DELETE http://localhost:3000/comments/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTI5NzkyMiwiZXhwIjoxNTkxMzg0MzIyfQ.1MKubc4FBoI60clEUxEy4F0BXarvTWixEeb6L5jHIRM

{
    "id":2 
}



###
DELETE http://localhost:3000/user/delete/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTU5MTI5OTE5MCwiZXhwIjoxNTkxMzg1NTkwfQ._5pHSJ0MwpHir0hLTotD8A8C7tQTBj6KS36mNT7_sno

{
    "userId": 1,
    "mail": "aze@aze.com",
    "mdp": "aze"
}



##################### PUT ###
###
PUT http://localhost:3000/posts/:id/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTU5MTI5ODY4MSwiZXhwIjoxNTkxMzg1MDgxfQ.sXKh0a07qG6g56N1ZiHVtqqZad1JQH7saUSXMcoFWY0

{
    "userId": 3,
    "id": 4,
    "title": "mon post modifié",
    "content": "mon premier post modifié",
    "url_image":"https://media.giphy.com/media/rY93u9tQbybks/giphy.gif"
}

###
PUT http://localhost:3000/comments/:id/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTU5MTI5NjgyNCwiZXhwIjoxNTkxMzgzMjI0fQ.KIDakStX0sPfb8aXn-kdjcOVcBa4DwoAzIohw0FhGnU

{
    "id": 10,
    "content": "mon premier commentaire modifié"
}